version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    container_name: server_django-postgres
    volumes:
      - .:/code
    ports:
      - 8000:8000